"""Detect transit-cluster and stop-level scheduling conflicts.

The script analyzes block-level transit data to flag times when more
buses are scheduled than a bay or cluster can physically handle. It
reads the block-level XLSX outputs generated by
``scripts.gtfs_exports.block_status_timeline_exporter`` (Step 1) -- or the
combined CSV that step can write -- calculates capacity constraints from the
user-defined ``CLUSTER_DEFINITIONS``, and writes a detailed Excel workbook for
each cluster showing every event and highlighting any conflicts.

Two kinds of conflict are checked:

- *Stop* conflicts: more buses occupying one stop (bay) in a minute than its
  capacity. Which statuses count as occupying the bay is controlled by
  ``PASSENGER_SERVICE_STATUSES`` and ``COUNT_IN_BAY_LAYOVER_AT_STOP``.
- *Cluster* conflicts: more buses present anywhere in the cluster (bays plus
  overflow/layover spaces) than the cluster can hold.

Outputs
-------
- ``<Cluster_Name>_Conflicts.xlsx`` (one workbook per cluster, written to
  ``CLUSTER_CONFLICT_OUTPUT_FOLDER``):
  * “Summary” -- Step 1 assumptions (if found), per-stop conflict tallies,
    and minute counts under three rules: any stop in conflict; two or more
    stops in conflict at once (the “one bus can use the layover space” rule);
    and conflicts that remain once buses already on the overflow space are
    counted against it.
  * “Conflict Events” -- one row per run of consecutive conflict minutes at a
    stop, naming the buses involved.
  * “Overflow Events” -- runs of minutes where a layover/overflow space holds
    more buses than it can, per space when ``OVERFLOW_ROUTING`` is set.
  * “Layover Runs” -- every stretch a block spends at the cluster between
    trips (or before its first / after its last), with in-bay vs. overflow
    minutes and a flag for short in-bay sits before departure.
  * “AllStops” -- every minute-row in the cluster, conflict rows bold and
    shaded, plus one sheet per stop and overflow bay.

Typical usage
-------------
Update the paths in the CONFIGURATION section and run from a Jupyter
notebook, ArcGIS Pro’s “Python” pane, or directly from the command line.
"""

from __future__ import annotations

import logging
import os
from typing import Any, Dict, List, Optional, Set, Tuple

import pandas as pd
from openpyxl.styles import Font, PatternFill
from openpyxl.worksheet.worksheet import Worksheet
from pandas import DataFrame

# ==================================================================================================
# CONFIGURATION
# ==================================================================================================

# Folder containing your block-level output from Step 1
BLOCK_OUTPUT_FOLDER: str = r"Path\To\Your\Input_Folder"

# Where to save the cluster-conflict outputs
CLUSTER_CONFLICT_OUTPUT_FOLDER: str = r"Path\To\Your\Output_Folder"

# Optional: must match Step 1's SCENARIO_NAME. Input is read from
# BLOCK_OUTPUT_FOLDER\<SCENARIO_NAME> and the workbook is named
# <Cluster>_Conflicts_<SCENARIO_NAME>.xlsx. Leave "" to use the folders as-is.
SCENARIO_NAME: str = ""

# Optional: the combined CSV Step 1 writes (``COMBINED_TIMELINE_FILE``). If
# this file exists in the input folder it is read instead of the per-block
# workbooks, which is much faster when re-running scenarios. Set to "" to
# always read the workbooks.
COMBINED_TIMELINE_FILE: str = r"all_blocks_timeline.csv"

# Optional: Step 1's assumptions file, echoed into the Summary sheet if present.
ASSUMPTIONS_FILE: str = r"timeline_assumptions.txt"

# Count a bus laying over *in its bay* (Step 1 status DWELL) as occupying that
# stop. Buses on the overflow/layover space (LAYOVER, LONG BREAK) never do.
COUNT_IN_BAY_LAYOVER_AT_STOP: bool = True

# Optional: which overflow bay a laying-over bus uses, by Step 1 status.
# LAYOVER is a between-trip gap longer than Step 1's IN_BAY_LAYOVER_MAX_MINUTES
# and up to its LAYOVER_THRESHOLD; LONG BREAK is longer. Keys must be
# overflow_bays of the cluster they apply to (entries are matched to each
# cluster by name). Leave empty to treat a cluster's overflow bays as one
# interchangeable pool. A bus bumped from a bay by a one-minute conflict is
# charged to BUMPED_TO_SPACE (a key here, or "" for the pool). Example:
#   OVERFLOW_ROUTING = {
#       "layover_bay_A": ["LAYOVER"],  # near space: medium layovers, and bumped buses
#       "layover_bay_B": ["LONG BREAK"],  # far space: long layovers only
#   }
#   BUMPED_TO_SPACE = "layover_bay_A"
OVERFLOW_ROUTING: Dict[str, List[str]] = {}
BUMPED_TO_SPACE: str = ""

# Flag layover runs spent entirely in a bay whose length falls in this range
# (inclusive, minutes) and that end with a departure -- the "sits in the bay
# for a few minutes before leaving" cases.
SIT_FLAG_MIN_MINUTES: int = 3
SIT_FLAG_MAX_MINUTES: int = 10

# Dictionary of clusters, including single_bay, double_bay, triple_bay, and overflow.
# Each key is the cluster name, the value is a dict with lists:
#   'single_bay_stops' -> capacity 1 each
#   'double_bay_stops' -> capacity 2 each
#   'triple_bay_stops' -> capacity 3 each
#   'overflow_bays'    -> capacity 1 each
# Stops are GTFS stop_ids; overflow bays are free-text names that Step 1 does
# not know about (they only ever hold laying-over buses).
CLUSTER_DEFINITIONS: Dict[str, Dict[str, List[str]]] = {
    "Park & Ride": {
        "single_bay_stops": ["3882", "3881"],
        "double_bay_stops": [],
        "triple_bay_stops": [],
        "overflow_bays": [],
    },
    "Metro": {
        "single_bay_stops": ["2373"],
        "double_bay_stops": ["2832"],
        "triple_bay_stops": [],
        "overflow_bays": ["layover_bay_A", "layover_bay_B"],
    },
}

# Define which statuses indicate bus presence in the cluster
PRESENCE_STATUSES: Set[str] = {
    "ARRIVE",
    "DEPART",
    "ARRIVE/DEPART",
    "DWELL",
    "LOADING",
    "LAYOVER",
    "LONG BREAK",
}

# Define which statuses indicate the bus is physically occupying a stop bay
# (DWELL is added at run time when COUNT_IN_BAY_LAYOVER_AT_STOP is True)
PASSENGER_SERVICE_STATUSES: Set[str] = {
    "ARRIVE",
    "DEPART",
    "ARRIVE/DEPART",
    "LOADING",
}

# Statuses spent on the overflow/layover space rather than in a bay
OVERFLOW_STATUSES: Set[str] = {"LAYOVER", "LONG BREAK"}

# Statuses that make up a "layover run" -- time at the cluster between trips
SIT_STATUSES: Set[str] = {"ARRIVE", "DWELL", "LOADING", "LAYOVER", "LONG BREAK"}

LOG_LEVEL: int = logging.INFO  # DEBUG / INFO / WARNING / ERROR

CONFLICT_FILL = PatternFill(start_color="FFF4CCCC", end_color="FFF4CCCC", fill_type="solid")

# ==================================================================================================
# FUNCTIONS
# ==================================================================================================


def bay_statuses() -> Set[str]:
    """Statuses that count as occupying a stop, honoring the in-bay layover switch."""
    if COUNT_IN_BAY_LAYOVER_AT_STOP:
        return PASSENGER_SERVICE_STATUSES | {"DWELL"}
    return set(PASSENGER_SERVICE_STATUSES)


def timestamp_to_minutes(ts: object) -> Optional[int]:
    """Convert an ``HH:MM`` timestamp (hours may exceed 24) to minutes past midnight."""
    if ts is None or pd.isna(ts):
        return None
    parts = str(ts).strip().split(":")
    if len(parts) < 2:
        return None
    try:
        return int(parts[0]) * 60 + int(parts[1])
    except ValueError:
        return None


def bus_label(row: pd.Series) -> str:
    """Short human-readable identifier for the bus on a timeline row."""
    route = str(row.get("Route Short Name") or row.get("Route") or "").strip()
    headsign = str(row.get("Trip Headsign") or "").strip()
    block = str(row.get("Block") or "").strip()
    trip = str(row.get("Trip ID") or "").strip()
    name = f"{route} {headsign}".strip() or "?"
    return f"{name} (blk {block}, trip {trip})"


def get_all_official_stops(cinfo: Dict[str, List[str]]) -> List[str]:
    """Return a combined list of all *official* stops in a cluster.

    Regardless of whether the stop is single-, double-, or triple-bay,
    overflow bays are *excluded* here because they do not count toward
    the “official” set used in certain analyses.

    Args:
    ----
    cinfo :
        The cluster-definition dictionary for a single cluster.

    Returns:
    -------
    list[str]
        Concatenated list of all official stop IDs.
    """
    return (
        cinfo.get("single_bay_stops", [])
        + cinfo.get("double_bay_stops", [])
        + cinfo.get("triple_bay_stops", [])
    )


def build_cluster_capacities() -> Dict[str, int]:
    """Compute total bay-capacity for every cluster.

    Capacity is calculated as::

        capacity = (#single * 1) + (#double * 2) + (#triple * 3) + (#overflow * 1)

    Returns:
    -------
    dict[str, int]
        Mapping of ``cluster_name -> capacity`` (number of buses that
        can be simultaneously present).
    """
    capacities: Dict[str, int] = {}
    for cname, cinfo in CLUSTER_DEFINITIONS.items():
        n_single = len(cinfo.get("single_bay_stops", []))
        n_double = len(cinfo.get("double_bay_stops", []))
        n_triple = len(cinfo.get("triple_bay_stops", []))
        n_overflow = len(cinfo.get("overflow_bays", []))

        cluster_cap = (1 * n_single) + (2 * n_double) + (3 * n_triple) + (1 * n_overflow)
        capacities[cname] = cluster_cap
    return capacities


def build_stop_capacities() -> Dict[str, int]:
    """Generate a per-stop capacity dictionary.

    Returns:
    -------
    dict[str, int]
        ``{stop_id: capacity}`` where single-bay = 1, double-bay = 2,
        triple-bay = 3, and overflow = 1.
    """
    stop_caps: Dict[str, int] = {}
    for cinfo in CLUSTER_DEFINITIONS.values():
        for stop_id in cinfo.get("single_bay_stops", []):
            stop_caps[str(stop_id)] = 1
        for stop_id in cinfo.get("double_bay_stops", []):
            stop_caps[str(stop_id)] = 2
        for stop_id in cinfo.get("triple_bay_stops", []):
            stop_caps[str(stop_id)] = 3
        for ovf in cinfo.get("overflow_bays", []):
            stop_caps[str(ovf)] = 1
    return stop_caps


# --------------------------------------------------------------------------------------------------
# CORE CONFLICT-DETECTION LOGIC
# --------------------------------------------------------------------------------------------------


def normalize_stop_id(stop_id: object) -> Optional[str]:
    """Return a normalized stop-ID string.

    Converts ``2956.0`` → ``"2956"`` and gracefully handles *NaN*.

    Args:
    ----
    stop_id :
        Value from the ``Stop ID`` column, potentially numeric or NaN.

    Returns:
    -------
    str | None
        Cleaned stop ID or *None* if ``stop_id`` is NaN.
    """
    if pd.isna(stop_id):
        return None
    sid_str = str(stop_id).strip()
    if sid_str.endswith(".0"):
        sid_str = sid_str[:-2]
    return sid_str


def assign_cluster_name(df_in: DataFrame) -> DataFrame:
    """Add a ``ClusterName`` column indicating which cluster each stop belongs to.

    If a stop appears in multiple clusters (unlikely), the first match in
    ``CLUSTER_DEFINITIONS`` wins.

    Args:
    ----------
    df_in :
        Input DataFrame containing at least a ``Stop ID`` column.

    Returns:
    -------
    pandas.DataFrame
        Copy of ``df_in`` with the additional ``ClusterName`` column.
    """
    df_out = df_in.copy()
    df_out["ClusterName"] = None

    # Build a map of cluster → set(stop_ids)
    cluster_map: Dict[str, Set[str]] = {}
    for cname, cinfo in CLUSTER_DEFINITIONS.items():
        official_stops = get_all_official_stops(cinfo)
        overflow = cinfo.get("overflow_bays", [])
        all_stops = official_stops + overflow
        cluster_map[cname] = set(map(str, all_stops))

    for cname, stop_set in cluster_map.items():
        mask = df_out["Stop ID"].isin(stop_set)
        df_out.loc[mask, "ClusterName"] = cname

    return df_out


def find_cluster_conflicts(df_in: DataFrame) -> Set[Tuple[str, str]]:
    """Identify cluster-level conflicts.

    A conflict occurs when the number of *present* buses exceeds the
    cluster’s capacity at a specific timestamp.

    Args:
    ----------
    df_in :
        DataFrame that already contains a ``ClusterName`` column.

    Returns:
    -------
    set[tuple[str, str]]
        {(cluster_name, timestamp), …} representing each conflict point.
    """
    cluster_caps = build_cluster_capacities()
    conflict_set: Set[Tuple[str, str]] = set()

    present_df = df_in[df_in["Status"].isin(PRESENCE_STATUSES)].copy()
    present_df = present_df.dropna(subset=["ClusterName"])  # ignore rows w/o cluster

    group = present_df.groupby(["ClusterName", "Timestamp"])
    for (cname, ts), grp in group:
        cap = cluster_caps.get(cname, 1)
        if len(grp) > cap:  # More vehicles than capacity
            conflict_set.add((cname, ts))

    return conflict_set


def find_stop_conflicts(df_in: DataFrame) -> Set[Tuple[str, str]]:
    """Identify stop-level conflicts.

    A conflict occurs when the number of buses in passenger-service
    statuses at a stop exceeds that stop’s capacity at a given timestamp.

    Args:
    ----------
    df_in :
        Raw DataFrame containing ``Stop ID`` and ``Status`` columns.

    Returns:
    -------
    set[tuple[str, str]]
        {(stop_id, timestamp), …} representing each conflict point.
    """
    stop_caps = build_stop_capacities()
    conflict_set: Set[Tuple[str, str]] = set()

    pass_df = df_in[df_in["Status"].isin(bay_statuses())].copy()
    # only stops with a defined capacity (cluster bays and overflow); other
    # stops in a block's day are not being assessed
    pass_df = pass_df[pass_df["Stop ID"].isin(stop_caps.keys())]

    group = pass_df.groupby(["Stop ID", "Timestamp"])
    for (sid, ts), grp in group:
        cap = stop_caps.get(sid, 1)
        if len(grp) > cap:
            conflict_set.add((sid, ts))

    return conflict_set


def annotate_conflicts(
    df_in: DataFrame,
    cluster_conflicts: Set[Tuple[str, str]],
    stop_conflicts: Set[Tuple[str, str]],
) -> DataFrame:
    """Append a ``ConflictType`` column categorizing each row.

    ``ConflictType`` will be one of ``{"NONE", "CLUSTER", "STOP", "BOTH"}``.

    Args:
    ----------
    df_in :
        Input DataFrame (must include ``ClusterName``, ``Stop ID``,
        ``Timestamp``).
    cluster_conflicts :
        Set of cluster-level conflict keys as produced by
        :func:`find_cluster_conflicts`.
    stop_conflicts :
        Set of stop-level conflict keys as produced by
        :func:`find_stop_conflicts`.

    Returns:
    -------
    pandas.DataFrame
        Copy of ``df_in`` with the additional ``ConflictType`` column.
    """
    df_out = df_in.copy()
    conflict_types: List[str] = []

    for _, row in df_out.iterrows():
        cname = row["ClusterName"]
        ts = row["Timestamp"]
        sid = row["Stop ID"]

        has_cluster_conf = pd.notna(cname) and (cname, ts) in cluster_conflicts
        has_stop_conf = sid is not None and (sid, ts) in stop_conflicts

        if has_cluster_conf and has_stop_conf:
            conflict_types.append("BOTH")
        elif has_cluster_conf:
            conflict_types.append("CLUSTER")
        elif has_stop_conf:
            conflict_types.append("STOP")
        else:
            conflict_types.append("NONE")

    df_out["ConflictType"] = conflict_types
    return df_out


# --------------------------------------------------------------------------------------------------
# REPORTS: CONFLICT EVENTS, TALLIES, LAYOVER RUNS
# --------------------------------------------------------------------------------------------------


def _stop_occupancy(df_in: DataFrame) -> DataFrame:
    """Rows that occupy a stop (bay), with a numeric minute column."""
    occ = df_in[df_in["Status"].isin(bay_statuses()) & df_in["Stop ID"].notna()].copy()
    occ["Minute"] = occ["Timestamp"].apply(timestamp_to_minutes)
    return occ.dropna(subset=["Minute"])


def build_conflict_events(df_in: DataFrame) -> DataFrame:
    """Collapse per-minute stop conflicts into events.

    An event is a run of consecutive minutes at one stop during which more
    buses occupy it than its capacity. Buses named on the event are every bus
    present at that stop during the run.

    Args:
    ----------
    df_in :
        Timeline rows for one cluster (must include ``Stop ID``, ``Stop
        Name``, ``Timestamp``, ``Status``, ``Block``).

    Returns:
    -------
    pandas.DataFrame
        One row per event: stop, window, length, bus count, bus labels.
    """
    stop_caps = build_stop_capacities()
    occ = _stop_occupancy(df_in)
    events: List[Dict[str, Any]] = []

    for stop_id, stop_df in occ.groupby("Stop ID"):
        cap = stop_caps.get(str(stop_id), 1)
        per_minute = stop_df.groupby("Minute")
        conflict_minutes = sorted(m for m, g in per_minute if len(g) > cap)
        if not conflict_minutes:
            continue
        stop_name = stop_df["Stop Name"].iloc[0]

        run_start = conflict_minutes[0]
        run_prev = run_start
        for m in conflict_minutes[1:] + [None]:
            if m is not None and m == run_prev + 1:
                run_prev = m
                continue
            window = stop_df[(stop_df["Minute"] >= run_start) & (stop_df["Minute"] <= run_prev)]
            labels = sorted({bus_label(r) for _, r in window.iterrows()})
            events.append(
                {
                    "Stop ID": stop_id,
                    "Stop Name": stop_name,
                    "Start": window["Timestamp"].min(),
                    "End": window["Timestamp"].max(),
                    "Minutes": int(run_prev - run_start + 1),
                    "Peak Buses": int(window.groupby("Minute").size().max()),
                    "Buses": len(labels),
                    "Bus 1": labels[0] if len(labels) > 0 else "",
                    "Bus 2": labels[1] if len(labels) > 1 else "",
                    "Bus 3": labels[2] if len(labels) > 2 else "",
                    "Others": "; ".join(labels[3:]),
                }
            )
            if m is not None:
                run_start = run_prev = m

    cols = [
        "Stop ID",
        "Stop Name",
        "Start",
        "End",
        "Minutes",
        "Peak Buses",
        "Buses",
        "Bus 1",
        "Bus 2",
        "Bus 3",
        "Others",
    ]
    out = DataFrame(events, columns=cols)
    return out.sort_values(["Start", "Stop ID"]).reset_index(drop=True)


def _cluster_routing(cluster_info: Dict[str, List[str]]) -> Dict[str, str]:
    """``status -> overflow space`` for one cluster.

    Only the ``OVERFLOW_ROUTING`` entries whose space is one of this cluster's
    ``overflow_bays`` apply, so a routing written for one facility does not
    leak into another. Empty when routing is off or nothing matches.
    """
    overflow_bays = {str(b) for b in cluster_info.get("overflow_bays", [])}
    status_to_space: Dict[str, str] = {}
    for space, statuses in OVERFLOW_ROUTING.items():
        if str(space) in overflow_bays:
            for status in statuses:
                status_to_space[status] = str(space)
    return status_to_space


def _validate_overflow_routing() -> None:
    """Warn about routing settings that can never apply to any configured cluster."""
    all_overflow = {
        str(b) for cinfo in CLUSTER_DEFINITIONS.values() for b in cinfo.get("overflow_bays", [])
    }
    for space in OVERFLOW_ROUTING:
        if str(space) not in all_overflow:
            logging.warning(
                "OVERFLOW_ROUTING space '%s' is not an overflow bay of any cluster; ignored.", space
            )
    if BUMPED_TO_SPACE and BUMPED_TO_SPACE not in OVERFLOW_ROUTING:
        logging.warning(
            "BUMPED_TO_SPACE '%s' is not a key of OVERFLOW_ROUTING; bumped buses are "
            "charged to the overflow pool instead.",
            BUMPED_TO_SPACE,
        )


def _overflow_rows(df_in: DataFrame, cluster_info: Dict[str, List[str]]) -> DataFrame:
    """Rows spent on the overflow space, with ``Minute`` and the ``Space`` each bus is routed to.

    With no routing for this cluster every row gets ``Space = "(pool)"``.
    Statuses not listed in the routing fall to the first overflow bay.
    """
    rows = df_in[df_in["Status"].isin(OVERFLOW_STATUSES) & df_in["Stop ID"].notna()].copy()
    rows["Minute"] = rows["Timestamp"].apply(timestamp_to_minutes)
    rows = rows.dropna(subset=["Minute"])
    overflow_bays = [str(b) for b in cluster_info.get("overflow_bays", [])]
    status_to_space = _cluster_routing(cluster_info)
    if not status_to_space or not overflow_bays:
        rows["Space"] = "(pool)"
        return rows
    rows["Space"] = rows["Status"].map(status_to_space).fillna(overflow_bays[0])
    return rows


def build_overflow_events(df_in: DataFrame, cluster_info: Dict[str, List[str]]) -> DataFrame:
    """Runs of consecutive minutes where an overflow space holds more buses than it can.

    Each routed space holds one bus. With routing off, the pool's capacity is
    the number of overflow bays.
    """
    rows = _overflow_rows(df_in, cluster_info)
    n_overflow = len(cluster_info.get("overflow_bays", []))
    events: List[Dict[str, Any]] = []
    for space, space_df in rows.groupby("Space"):
        cap = n_overflow if space == "(pool)" else 1
        over = sorted(m for m, g in space_df.groupby("Minute") if len(g) > cap)
        if not over:
            continue
        run_start = run_prev = over[0]
        for m in over[1:] + [None]:
            if m is not None and m == run_prev + 1:
                run_prev = m
                continue
            window = space_df[(space_df["Minute"] >= run_start) & (space_df["Minute"] <= run_prev)]
            labels = sorted({bus_label(r) for _, r in window.iterrows()})
            events.append(
                {
                    "Space": space,
                    "Capacity": cap,
                    "Start": window["Timestamp"].min(),
                    "End": window["Timestamp"].max(),
                    "Minutes": int(run_prev - run_start + 1),
                    "Peak Buses": int(window.groupby("Minute").size().max()),
                    "Buses": len(labels),
                    "Bus 1": labels[0] if len(labels) > 0 else "",
                    "Bus 2": labels[1] if len(labels) > 1 else "",
                    "Bus 3": labels[2] if len(labels) > 2 else "",
                    "Others": "; ".join(labels[3:]),
                }
            )
            if m is not None:
                run_start = run_prev = m
    cols = [
        "Space",
        "Capacity",
        "Start",
        "End",
        "Minutes",
        "Peak Buses",
        "Buses",
        "Bus 1",
        "Bus 2",
        "Bus 3",
        "Others",
    ]
    return DataFrame(events, columns=cols).sort_values(["Start", "Space"]).reset_index(drop=True)


def build_minute_rules(df_in: DataFrame, cluster_info: Dict[str, List[str]]) -> Dict[str, Any]:
    """Count conflict minutes for one cluster under three rules.

    Rules
    -----
    ``any_stop``
        Minutes with at least one stop over capacity.
    ``two_or_more_stops``
        Minutes with two or more stops over capacity at once. This is the
        "a single-bay conflict is resolved by one bus using the layover
        space" rule, taken at face value (the space is assumed free).
    ``overflow_adjusted``
        Minutes where the excess buses across all stops, plus buses already
        on the overflow space (LAYOVER / LONG BREAK), exceed the number of
        overflow bays defined for the cluster. With ``OVERFLOW_ROUTING`` set,
        the excess is charged to ``BUMPED_TO_SPACE`` only and compared with
        that space's occupancy (capacity 1).

    Also returns per-space peak occupancy and over-capacity minutes under
    ``per_space``.
    """
    stop_caps = build_stop_capacities()
    n_overflow = len(cluster_info.get("overflow_bays", []))

    occ = _stop_occupancy(df_in)
    excess_by_minute: Dict[int, int] = {}
    stops_over_by_minute: Dict[int, int] = {}
    for (stop_id, minute), g in occ.groupby(["Stop ID", "Minute"]):
        over = len(g) - stop_caps.get(str(stop_id), 1)
        if over > 0:
            excess_by_minute[minute] = excess_by_minute.get(minute, 0) + over
            stops_over_by_minute[minute] = stops_over_by_minute.get(minute, 0) + 1

    on_overflow = _overflow_rows(df_in, cluster_info)
    overflow_by_minute = on_overflow.groupby("Minute").size().to_dict()

    per_space: Dict[str, Dict[str, int]] = {}
    for space, space_df in on_overflow.groupby("Space"):
        cap = n_overflow if space == "(pool)" else 1
        by_minute = space_df.groupby("Minute").size()
        per_space[str(space)] = {
            "capacity": cap,
            "peak": int(by_minute.max()) if len(by_minute) else 0,
            "minutes_over": int((by_minute > cap).sum()),
            "minutes_used": int(len(by_minute)),
        }

    routed_spaces = set(_cluster_routing(cluster_info).values())
    bumped_to = BUMPED_TO_SPACE if BUMPED_TO_SPACE in routed_spaces else ""
    if bumped_to:
        bump_df = on_overflow[on_overflow["Space"] == bumped_to]
        bump_by_minute = bump_df.groupby("Minute").size().to_dict()
        overflow_adjusted = sum(
            1 for m, ex in excess_by_minute.items() if ex + bump_by_minute.get(m, 0) > 1
        )
    else:
        overflow_adjusted = sum(
            1
            for m, ex in excess_by_minute.items()
            if ex + overflow_by_minute.get(m, 0) > n_overflow
        )

    return {
        "any_stop": len(excess_by_minute),
        "two_or_more_stops": sum(1 for n in stops_over_by_minute.values() if n >= 2),
        "overflow_adjusted": overflow_adjusted,
        "overflow_capacity": n_overflow,
        "peak_on_overflow": int(max(overflow_by_minute.values(), default=0)),
        "minutes_overflow_over_capacity": sum(
            1 for n in overflow_by_minute.values() if n > n_overflow
        ),
        "per_space": per_space,
        "bumped_to": bumped_to or "(pool)",
    }


def build_bay_tally(df_in: DataFrame, events: DataFrame) -> DataFrame:
    """Per-stop conflict minutes and events, one row per stop."""
    stop_caps = build_stop_capacities()
    occ = _stop_occupancy(df_in)
    rows: List[Dict[str, Any]] = []
    for stop_id, stop_df in occ.groupby("Stop ID"):
        cap = stop_caps.get(str(stop_id), 1)
        minutes = sum(1 for _, g in stop_df.groupby("Minute") if len(g) > cap)
        rows.append(
            {
                "Stop ID": stop_id,
                "Stop Name": stop_df["Stop Name"].iloc[0],
                "Capacity": cap,
                "Conflict Minutes": minutes,
                "Conflict Events": int((events["Stop ID"] == stop_id).sum())
                if not events.empty
                else 0,
            }
        )
    return DataFrame(
        rows, columns=["Stop ID", "Stop Name", "Capacity", "Conflict Minutes", "Conflict Events"]
    )


def _txt(value: object) -> str:
    """Cell value as text, with ``None``/NaN as an empty string."""
    return "" if value is None or pd.isna(value) else str(value)


def _layover_run_row(
    block: object,
    current: List[Dict[str, Any]],
    after_status: str,
    after_stop: str,
    trip_lookup: Dict[str, str],
    has_prev_next: bool,
    occupying: Set[str],
) -> Dict[str, Any]:
    """Summarize one layover run (consecutive cluster minutes of a block) as a row.

    Args:
        block: Block ID the run belongs to.
        current: The run's timeline rows in minute order (non-empty).
        after_status: Status of the row that ended the run (``"END"`` at the
            end of the block's day).
        after_stop: Stop ID of that row, if it has one.
        trip_lookup: ``trip_id -> "route headsign"`` labels.
        has_prev_next: Whether the timeline carries ``Prev Trip ID`` /
            ``Next Trip ID`` columns (Step 1 writes them).
        occupying: Statuses that count as in-bay (see :func:`bay_statuses`).

    Returns:
        One ``Layover Runs`` row.
    """
    statuses = [r["Status"] for r in current]
    in_bay = sum(1 for st in statuses if st in occupying or st == "DWELL")
    overflow = sum(1 for st in statuses if st in OVERFLOW_STATUSES)
    first, last = current[0], current[-1]
    prev_tid = _txt(first.get("Prev Trip ID")) if has_prev_next else ""
    next_tid = _txt(last.get("Next Trip ID")) if has_prev_next else ""
    if first["Status"] == "ARRIVE" and not prev_tid:
        prev_tid = _txt(first.get("Trip ID"))
    if last["Status"] == "LOADING" and not next_tid:
        next_tid = _txt(last.get("Trip ID"))
    if not prev_tid:
        run_type = "pull-out"
    elif not next_tid:
        run_type = "pull-in"
    elif overflow:
        run_type = "overflow"
    else:
        run_type = "in bay"
    total = int(last["Minute"] - first["Minute"] + 1)
    flag = (
        run_type == "in bay"
        and after_status == "DEPART"
        and SIT_FLAG_MIN_MINUTES <= total <= SIT_FLAG_MAX_MINUTES
    )
    # the stop the next trip actually departs from (its DEPART row), when the run ends in one
    if after_status == "DEPART" and after_stop:
        departure_stop = after_stop
    else:
        departure_stop = _txt(last.get("Stop ID"))
    return {
        "Block": block,
        "Type": run_type,
        "Flag": "YES" if flag else "",
        "Start": first["Timestamp"],
        "End": last["Timestamp"],
        "Total Minutes": total,
        "In-Bay Minutes": in_bay,
        "Overflow Minutes": overflow,
        "Arrival Stop": _txt(first.get("Stop ID")),
        "Departure Stop": departure_stop,
        "Arriving Trip": trip_lookup.get(prev_tid, ""),
        "Arriving Trip ID": prev_tid,
        "Departing Trip": trip_lookup.get(next_tid, ""),
        "Departing Trip ID": next_tid,
        "Ends With": after_status,
    }


def build_layover_runs(df_in: DataFrame) -> DataFrame:
    """List every stretch a block spends at the cluster between trips.

    A run is a maximal sequence of consecutive minutes for one block whose
    status is in ``SIT_STATUSES`` and whose stop is in the cluster. Runs are
    typed ``in bay`` (all minutes in a bay), ``overflow`` (some minutes on
    the overflow space), ``pull-out`` (no previous trip) or ``pull-in`` (no
    next trip). ``Flag`` marks in-bay runs ending in a departure whose length
    is between ``SIT_FLAG_MIN_MINUTES`` and ``SIT_FLAG_MAX_MINUTES``.

    Args:
    ----------
    df_in :
        Timeline rows for one cluster's blocks (all statuses, so the row
        after a run can be inspected). Needs ``ClusterName``.

    Returns:
    -------
    pandas.DataFrame
        One row per run.
    """
    df = df_in.copy()
    df["Minute"] = df["Timestamp"].apply(timestamp_to_minutes)
    df = df.dropna(subset=["Minute"]).sort_values(["Block", "Minute"])
    has_prev_next = "Prev Trip ID" in df.columns and "Next Trip ID" in df.columns

    # trip -> readable label, from rows that carry trip details
    trip_lookup: Dict[str, str] = {}
    for _, r in df[df["Trip ID"].notna() & (df["Trip ID"].astype(str) != "")].iterrows():
        tid = str(r["Trip ID"])
        if tid not in trip_lookup:
            route = str(r.get("Route Short Name") or r.get("Route") or "").strip()
            headsign = str(r.get("Trip Headsign") or "").strip()
            trip_lookup[tid] = f"{route} {headsign}".strip()

    occupying = bay_statuses()
    runs: List[Dict[str, Any]] = []
    for block, g in df.groupby("Block", sort=False):
        current: List[Dict[str, Any]] = []
        for r in g.to_dict("records"):
            in_cluster = pd.notna(r.get("ClusterName")) and r["Status"] in SIT_STATUSES
            if in_cluster and (not current or r["Minute"] == current[-1]["Minute"] + 1):
                current.append(r)
                continue
            if current:
                runs.append(
                    _layover_run_row(
                        block,
                        current,
                        str(r["Status"]),
                        _txt(r.get("Stop ID")),
                        trip_lookup,
                        has_prev_next,
                        occupying,
                    )
                )
                current = []
            if in_cluster:
                current.append(r)
        if current:
            runs.append(
                _layover_run_row(block, current, "END", "", trip_lookup, has_prev_next, occupying)
            )

    cols = [
        "Block",
        "Type",
        "Flag",
        "Start",
        "End",
        "Total Minutes",
        "In-Bay Minutes",
        "Overflow Minutes",
        "Arrival Stop",
        "Departure Stop",
        "Arriving Trip",
        "Arriving Trip ID",
        "Departing Trip",
        "Departing Trip ID",
        "Ends With",
    ]
    out = DataFrame(runs, columns=cols)
    return out.sort_values(["Start", "Block"]).reset_index(drop=True)


# --------------------------------------------------------------------------------------------------
# I/O AND EXCEL WRITING LOGIC
# --------------------------------------------------------------------------------------------------


def gather_block_spreadsheets(block_folder: str) -> DataFrame:
    """Read and concatenate every ``block_*.xlsx`` spreadsheet in *block_folder*.

    Args:
    ----------
    block_folder :
        Directory containing the Step 1 block-level output workbooks.

    Returns:
    -------
    pandas.DataFrame
        Combined DataFrame of all block files.

    Raises:
    ------
    FileNotFoundError
        If no eligible ``block_*.xlsx`` files are found.
    """
    all_files = [
        f
        for f in os.listdir(block_folder)
        if f.lower().endswith(".xlsx") and f.startswith("block_")
    ]
    if not all_files:
        raise FileNotFoundError(f"No block_*.xlsx files found in {block_folder}.")

    big_df_list: List[DataFrame] = []
    for fname in all_files:
        path = os.path.join(block_folder, fname)
        temp_df = pd.read_excel(path, dtype=str)  # keep IDs and route names as text
        temp_df["FileName"] = fname
        big_df_list.append(temp_df)

    df_combined = pd.concat(big_df_list, ignore_index=True)
    logging.info("Loaded %d total rows from Step 1 block XLSX files.", len(df_combined))
    return df_combined


def run_input_folder() -> str:
    """Folder Step 1 wrote this scenario to."""
    return (
        os.path.join(BLOCK_OUTPUT_FOLDER, SCENARIO_NAME) if SCENARIO_NAME else BLOCK_OUTPUT_FOLDER
    )


def load_timeline(block_folder: str) -> DataFrame:
    """Load Step 1 output: the combined CSV if configured and present, else the block workbooks."""
    if COMBINED_TIMELINE_FILE:
        combined_path = os.path.join(block_folder, COMBINED_TIMELINE_FILE)
        if os.path.isfile(combined_path):
            df = pd.read_csv(combined_path, dtype=str, keep_default_na=False)
            df = df.replace({"": None})
            logging.info("Loaded %d rows from %s.", len(df), combined_path)
            return df
        logging.info("No %s found; reading block_*.xlsx instead.", COMBINED_TIMELINE_FILE)
    return gather_block_spreadsheets(block_folder)


def read_assumptions(block_folder: str) -> List[str]:
    """Return the lines of Step 1's assumptions file, or an empty list if absent."""
    if not ASSUMPTIONS_FILE:
        return []
    path = os.path.join(block_folder, ASSUMPTIONS_FILE)
    if not os.path.isfile(path):
        return []
    with open(path, encoding="utf-8") as handle:
        return [line.rstrip("\n") for line in handle if line.strip()]


_PLACEHOLDER_MARKERS: Tuple[str, ...] = (
    "path\\to\\your",
    "your\\file\\path",
    "your\\folder\\path",
    "path/to/your",
    "your/file/path",
    "your/folder/path",
)


def _is_placeholder_path(p: str) -> bool:
    """Return True if *p* still points at a default placeholder location."""
    s = str(p).lower()
    return any(marker in s for marker in _PLACEHOLDER_MARKERS)


def _highlight_conflict_rows(worksheet: Worksheet, frame: DataFrame) -> None:
    """Bold and shade the rows of *frame* on *worksheet* whose ConflictType is not NONE."""
    conflict_col = int(frame.columns.get_loc("ConflictType")) + 1  # 1-based
    for row_idx in range(2, len(frame) + 2):  # data starts on row 2
        if worksheet.cell(row=row_idx, column=conflict_col).value != "NONE":
            for col_idx in range(1, len(frame.columns) + 1):
                cell = worksheet.cell(row=row_idx, column=col_idx)
                cell.font = Font(bold=True)
                cell.fill = CONFLICT_FILL


def _write_summary_sheet(
    writer: pd.ExcelWriter,
    cname: str,
    cinfo: Dict[str, List[str]],
    assumptions: List[str],
    tally: DataFrame,
    rules: Dict[str, Any],
    n_cluster_conflicts: int,
) -> None:
    """Write the Summary sheet: assumptions, per-stop tally, and minute counts by rule."""
    lines: List[Tuple[str, Any]] = [("Cluster", cname)]
    lines += [("Step 1 assumption", a) for a in assumptions] or [
        ("Step 1 assumption", "(no assumptions file found)")
    ]
    lines += [
        ("Stop occupancy statuses", ", ".join(sorted(bay_statuses()))),
        ("Overflow bays defined", rules["overflow_capacity"]),
        ("", ""),
        ("Minutes with any stop over capacity", rules["any_stop"]),
        (
            "Minutes with 2+ stops over capacity "
            "(single-stop conflicts assumed absorbed by layover space)",
            rules["two_or_more_stops"],
        ),
        (
            "Minutes over capacity after counting buses already on the overflow space "
            f"(bumped bus goes to {rules['bumped_to']})",
            rules["overflow_adjusted"],
        ),
        ("Minutes the whole cluster (bays + overflow) is over capacity", n_cluster_conflicts),
        ("", ""),
        ("Overflow spaces, all together: peak buses at once", rules["peak_on_overflow"]),
        (
            "Overflow spaces, all together: minutes over combined capacity",
            rules["minutes_overflow_over_capacity"],
        ),
    ]
    for space, stats in rules["per_space"].items():
        lines += [
            (
                f"{space}: statuses routed here",
                ", ".join(OVERFLOW_ROUTING.get(space, [])) if space != "(pool)" else "all",
            ),
            (f"{space}: minutes in use", stats["minutes_used"]),
            (f"{space}: peak buses at once (capacity {stats['capacity']})", stats["peak"]),
            (f"{space}: minutes over capacity", stats["minutes_over"]),
        ]
    header = DataFrame(lines, columns=["Item", "Value"])
    header.to_excel(writer, sheet_name="Summary", index=False)
    tally_with_total = pd.concat(
        [
            tally,
            DataFrame(
                [
                    {
                        "Stop ID": "Total",
                        "Stop Name": "",
                        "Capacity": "",
                        "Conflict Minutes": tally["Conflict Minutes"].sum(),
                        "Conflict Events": tally["Conflict Events"].sum(),
                    }
                ]
            ),
        ],
        ignore_index=True,
    )
    tally_with_total.to_excel(writer, sheet_name="Summary", index=False, startrow=len(header) + 3)
    ws = writer.sheets["Summary"]
    ws.column_dimensions["A"].width = 60
    ws.column_dimensions["B"].width = 40


def run_step2_conflict_detection() -> None:
    """Execute the full Step 2 conflict-detection workflow.

    Steps
    -----
    1. Read Step 1 output from :pydata:`BLOCK_OUTPUT_FOLDER` (combined CSV
       if present, else the block-level workbooks).
    2. Normalise stop IDs, assign clusters, find conflicts.
    3. For each cluster, build an Excel workbook containing Summary,
       Conflict Events and Layover Runs sheets, an “AllStops” sheet (all
       minute-rows, conflict rows bold and shaded), and one sheet per
       stop/overflow bay.
    4. Print summary statistics.

    Raises:
    ------
    ValueError
        If required columns are missing from the input spreadsheets.
    """
    logging.info("=== Step 2: Conflict detection and per-cluster output (multi-bay) ===")

    in_folder = run_input_folder()
    if not os.path.isdir(in_folder):
        logging.warning(
            "Input folder does not exist: %s. Run Step 1 with the same SCENARIO_NAME first.",
            in_folder,
        )
        return

    os.makedirs(CLUSTER_CONFLICT_OUTPUT_FOLDER, exist_ok=True)
    _validate_overflow_routing()

    # 1) Gather Step 1 data
    df = load_timeline(in_folder)
    assumptions = read_assumptions(in_folder)

    # Basic checks/cleanup
    required_cols = [
        "Timestamp",
        "Trip ID",
        "Block",
        "Route",
        "Direction",
        "Stop ID",
        "Stop Name",
        "Stop Sequence",
        "Arrival Time",
        "Departure Time",
        "Status",
    ]
    missing_cols = [c for c in required_cols if c not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing columns in block-level data: {missing_cols}")
    for optional in (
        "Route Short Name",
        "Trip Headsign",
        "Layover Location",
        "Prev Trip ID",
        "Next Trip ID",
    ):
        if optional not in df.columns:
            df[optional] = None

    # Normalize Stop ID text
    df["Stop ID"] = df["Stop ID"].apply(normalize_stop_id)
    # Ensure string Timestamps
    df["Timestamp"] = df["Timestamp"].astype(str).str.strip()

    # 2) Assign cluster, detect conflicts, annotate
    df = assign_cluster_name(df)
    cluster_conflicts = find_cluster_conflicts(df)
    stop_conflicts = find_stop_conflicts(df)
    df_annotated = annotate_conflicts(df, cluster_conflicts, stop_conflicts)

    # 3) Write results per cluster, each cluster → single XLSX with multiple sheets
    for cname, cinfo in CLUSTER_DEFINITIONS.items():
        # Combine all official stops + overflow for that cluster
        official_stops = get_all_official_stops(cinfo)
        overflow_stops = cinfo.get("overflow_bays", [])
        all_cluster_stops = official_stops + overflow_stops

        sub = df_annotated[df_annotated["ClusterName"] == cname].copy()
        if sub.empty:
            logging.info("No rows found for cluster '%s'. Skipping.", cname)
            continue
        # every row of every block that touches this cluster (layover runs need
        # to see the status that follows a run, which is not a cluster row)
        cluster_blocks = df_annotated[df_annotated["Block"].isin(sub["Block"].unique())]

        events = build_conflict_events(sub)
        tally = build_bay_tally(sub, events)
        rules = build_minute_rules(sub, cinfo)
        overflow_events = build_overflow_events(sub, cinfo)
        runs = build_layover_runs(cluster_blocks)
        n_cluster_conflicts = sum(1 for c, _ in cluster_conflicts if c == cname)

        safe_name = cname.replace(" ", "_")
        suffix = f"_{SCENARIO_NAME}" if SCENARIO_NAME else ""
        out_path = os.path.join(
            CLUSTER_CONFLICT_OUTPUT_FOLDER,
            f"{safe_name}_Conflicts{suffix}.xlsx",
        )
        logging.info("Building conflict output for cluster '%s' → %s", cname, out_path)

        # Sort by timestamp, then by block or stop ID
        sub = sub.sort_values(["Timestamp", "Block", "Stop ID"])

        with pd.ExcelWriter(out_path, engine="openpyxl") as writer:
            # 3a) Summary, Conflict Events, Layover Runs
            _write_summary_sheet(
                writer, cname, cinfo, assumptions, tally, rules, n_cluster_conflicts
            )
            events.to_excel(writer, sheet_name="Conflict Events", index=False)
            overflow_events.to_excel(writer, sheet_name="Overflow Events", index=False)
            runs.to_excel(writer, sheet_name="Layover Runs", index=False)

            # 3b) “AllStops” sheet, conflict rows bold and shaded
            sub.to_excel(writer, sheet_name="AllStops", index=False)
            _highlight_conflict_rows(writer.sheets["AllStops"], sub)

            # 3c) One sheet per stop
            for stop_id in all_cluster_stops:
                sid_str = str(stop_id)
                stop_df = sub[sub["Stop ID"] == sid_str].copy()
                if stop_df.empty:
                    continue

                # Make a sheet name that is safe in Excel (≤31 chars)
                sheet_name = f"Stop_{sid_str}"
                if len(sheet_name) > 31:
                    sheet_name = sheet_name[:31]

                stop_df.to_excel(writer, sheet_name=sheet_name, index=False)
                _highlight_conflict_rows(writer.sheets[sheet_name], stop_df)

        logging.info(" → Completed writing %s", out_path)
        logging.info(
            "   %s: %d conflict events across %d stop-minutes; "
            "%d layover runs (%d flagged %d-%d min in bay)",
            cname,
            len(events),
            int(tally["Conflict Minutes"].sum()),
            len(runs),
            int((runs["Flag"] == "YES").sum()) if not runs.empty else 0,
            SIT_FLAG_MIN_MINUTES,
            SIT_FLAG_MAX_MINUTES,
        )

    # Final conflict summary stats
    logging.info("\nDistinct cluster-conflict points: %d", len(cluster_conflicts))
    logging.info("Distinct stop-conflict points: %d", len(stop_conflicts))
    logging.info("Step 2 complete.")
    logging.info("bay_usage_analyzer.py completed successfully.")


# ==================================================================================================
# MAIN
# ==================================================================================================


def main() -> int:
    """Entry point when executing this module as a script.

    Returns:
        Process exit code: 0 on success, 1 on failure, 2 if required
        CONFIGURATION values are still placeholders.
    """
    logging.basicConfig(
        level=LOG_LEVEL,
        format="%(asctime)s | %(levelname)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    if _is_placeholder_path(BLOCK_OUTPUT_FOLDER) or _is_placeholder_path(
        CLUSTER_CONFLICT_OUTPUT_FOLDER
    ):
        logging.warning(
            "BLOCK_OUTPUT_FOLDER and/or CLUSTER_CONFLICT_OUTPUT_FOLDER are still set to "
            "placeholder values. Please update them in the CONFIGURATION section before running."
        )
        return 2
    run_step2_conflict_detection()
    logging.info("Script completed successfully.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
